name: secret-scanning

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main    
jobs:
  secret-scanning:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      # Infiscal CLI
      # TODO: Set a specific version
      - name: install Infiscal CLI
        run: |
          curl -1sLf \
          'https://artifacts-cli.infisical.com/setup.deb.sh' \
          | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      # exit code 1 if secret is found
      - name: run secret scanning
        run: |
          infisical scan --verbose --report-path secret-scanning-report.json

      # print the scan results (no matter the exit code)
      - name: print scan results
        if: always()
        run: |
          cat secret-scanning-report.json